<?php
/**
* 
* https://www.drupal.org/node/1887016
* My Google Custom Search Engine
*
* This search is set up to work with the two page search option. See: www.google.co.uk/cse/
*
*/


function mygooglecse_block_info() {
  // This example comes from node.module.
  $blocks['google_custom_search'] = array(
    'info' => t('My Google Custom Search'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}



function mygooglecse_block_view($delta = '') {
  // This example is adapted from node.module.
  $block['title'] = t('');
  $block['content'] = array(
   // '#markup' => '<gcse:searchbox-only queryParameterName="my_gcs"></gcse:searchbox-only>',
    '#attached' => array(
        'js' => array(
          drupal_get_path('module', 'mygooglecse') . '/mygooglecse.js',
      ),
    ),
  );
  return $block;
}



/**
 * Implements hook_permission().
 */
function mygooglecse_permission() {
  return array(
    'use_google_custom_search' => array(
      'title' => t('Use google custom search'),
      'description' => t('Who can have access to the google search results page.'),
    ),
  );
}




/**
* Implementation of hook_menu()
*/
function mygooglecse_menu() {
  // Here we set up the page where the results will display:
  $items['my_search/google'] = array(  // Change this url to wherever you want the page to be
    'title' => 'Search ',
    'description' => 'My Google Custom Search',
    'page callback' => 'mygooglecse_searchpage', // The function that will be called to set up the search page
    'access arguments' => array('use_google_custom_search'), // Those with this permission will be allowed to see the results
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}




// Here we set up the page:
function mygooglecse_searchpage() {

  // Now create the content of your page:
  $content = '';
  
  // This is the search box again - so that it also appears at the top of the search  page.
  $content .= '<gcse:searchbox-only queryParameterName="my_gcs"></gcse:searchbox-only>';
  
  // Drupal search link:
  // This creates a link to the Drupal standard search from the Google results page:
  //$content .= l(t('Advanced search'), 'search/node/' . $_GET['my_gcs']);
  
  // This is the code for the results list.
  // Note we also add the queryParameterName setting here to the code. See developers.google.com/custom-search/docs/element#supported_attributes for a full list of supported attributes.
  // I've also set it so links to pages in the results open in the same window rather  than a new tab/window which is the default.
  $content .= '<gcse:searchresults-only queryParameterName="my_gcs" linkTarget="_self"></gcse:searchresults-only>';
  
  return $content;
}
?>